version = 0.1
[default.deploy.parameters]
stack_name = "todo-list-aws"
resolve_s3 = true
s3_prefix = "todo-list-aws"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"production\""
image_repositories = []
